// Export utilities
export { cn } from './lib/utils'

// Export color system
export { 
  componentColors, 
  lightColors, 
  darkColors, 
  defaultColors,
  getColorValue,
  createCSSVariables 
} from './lib/colors'

// Export core components (always included)
export { Button } from './components/button'
export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from './components/card'
export { Input } from './components/input'
export { Label } from './components/label'
export { Textarea } from './components/textarea'
export { Select } from './components/select'
export { Checkbox } from './components/checkbox'
export { Switch } from './components/switch'
export { Alert } from './components/alert'
export { Modal } from './components/modal'
export { Progress } from './components/progress'
export { Radio } from './components/radio'
export { Rating } from './components/rating'
export { Skeleton } from './components/skeleton'
export { Breadcrumbs } from './components/breadcrumbs'
export { Table } from './components/table'
export { Popover } from './components/popover'

// Export advanced components (optional - can be imported separately)
export { Calendar } from './components/calendar'
export { TimePicker } from './components/timepicker'
export { Navbar } from './components/navbar'
export { Sidebar } from './components/sidebar'
export { Layout } from './components/layout'
export { Accordion } from './components/accordion'
export { Tabs } from './components/tabs'
export { Slider } from './components/slider'
export { Toast } from './components/toast'

// Export new components
export { Badge } from './components/badge'
export { Avatar, AvatarGroup } from './components/avatar'
export { Tooltip } from './components/tooltip'
export { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogFooter, DialogTitle, DialogDescription } from './components/dialog'
export { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuLabel, DropdownMenuGroup } from './components/dropdown-menu'
export { Separator } from './components/separator'
export { Toggle, ToggleGroup } from './components/toggle'
export { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogFooter, AlertDialogTitle, AlertDialogDescription, AlertDialogAction, AlertDialogCancel } from './components/alert-dialog'
export { Collapsible, CollapsibleTrigger, CollapsibleContent } from './components/collapsible'
export { ContextMenu, ContextMenuTrigger, ContextMenuContent, ContextMenuItem, ContextMenuSeparator, ContextMenuLabel, ContextMenuGroup } from './components/context-menu'
export { HoverCard, HoverCardTrigger, HoverCardContent } from './components/hover-card'
export { Combobox } from './components/combobox'
export { Pagination, PaginationItem } from './components/pagination'
export { RadioGroup, RadioGroupItem } from './components/radio-group'
export { Sheet, SheetTrigger, SheetContent, SheetHeader, SheetFooter, SheetTitle, SheetDescription } from './components/sheet'
export { ScrollArea, ScrollBar } from './components/scroll-area'
export { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink } from './components/navigation-menu'
export { Menubar, MenubarMenu, MenubarTrigger, MenubarContent, MenubarItem, MenubarSeparator, MenubarLabel, MenubarGroup } from './components/menubar'
export { Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem, CommandSeparator } from './components/command'
export { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext, CarouselIndicator } from './components/carousel'
export { InputOTP, InputOTPGroup, InputOTPSlot } from './components/input-otp'
export { Resizable, ResizableHandle, ResizablePanel } from './components/resizable'
export { DatePicker, DatePickerInput, DatePickerContent, DatePickerCalendar } from './components/date-picker'
export { AspectRatio } from './components/aspect-ratio'
export { Drawer, DrawerTrigger, DrawerContent, DrawerHeader, DrawerFooter, DrawerTitle, DrawerDescription } from './components/drawer'
export { TypographyH1, TypographyH2, TypographyH3, TypographyH4, TypographyH5, TypographyH6, TypographyP, TypographyBlockquote, TypographyCode, TypographyLead, TypographyLarge, TypographySmall, TypographyMuted } from './components/typography'
export { DataTable, DataTableHeader, DataTableRow, DataTablePagination } from './components/data-table'
export { Chart, BarChart, LineChart, PieChart, DoughnutChart } from './components/chart'
export { Sonner, useToasts } from './components/sonner'
export { Form, FormField, FormItem, FormLabel, FormControl, FormDescription, FormMessage, FormError, FormSuccess, FormWarning } from './components/react-hook-form'

// Export types
export type { ButtonProps } from './components/button'
export type { CardProps, CardContentProps, CardDescriptionProps, CardFooterProps, CardHeaderProps, CardTitleProps } from './components/card'
export type { InputProps } from './components/input'
export type { LabelProps } from './components/label'
export type { TextareaProps } from './components/textarea'
export type { SelectProps, SelectOption } from './components/select'
export type { CheckboxProps } from './components/checkbox'
export type { SwitchProps } from './components/switch'
export type { AlertProps } from './components/alert'
export type { ModalProps } from './components/modal'
export type { ProgressProps } from './components/progress'
export type { RadioProps } from './components/radio'
export type { RatingProps } from './components/rating'
export type { SkeletonProps } from './components/skeleton'
export type { BreadcrumbsProps, BreadcrumbItem } from './components/breadcrumbs'
export type { TableProps, TableColumn } from './components/table'
export type { PopoverProps } from './components/popover'
export type { CalendarProps } from './components/calendar'
export type { TimePickerProps } from './components/timepicker'
export type { NavbarProps } from './components/navbar'
export type { SidebarProps, SidebarItem } from './components/sidebar'
export type { LayoutProps } from './components/layout'
export type { AccordionProps, AccordionItem } from './components/accordion'
export type { TabsProps, TabItem } from './components/tabs'
export type { SliderProps } from './components/slider'
export type { ToastProps } from './components/toast'

// Export new component types
export type { BadgeProps } from './components/badge'
export type { AvatarProps } from './components/avatar'
export type { TooltipProps } from './components/tooltip'
export type { DialogProps, DialogTriggerProps, DialogContentProps, DialogHeaderProps, DialogFooterProps, DialogTitleProps, DialogDescriptionProps } from './components/dialog'
export type { DropdownMenuProps, DropdownMenuTriggerProps, DropdownMenuContentProps, DropdownMenuItemProps, DropdownMenuSeparatorProps, DropdownMenuLabelProps, DropdownMenuGroupProps } from './components/dropdown-menu'
export type { SeparatorProps } from './components/separator'
export type { ToggleProps, ToggleGroupProps } from './components/toggle'
export type { AlertDialogProps, AlertDialogTriggerProps, AlertDialogContentProps, AlertDialogHeaderProps, AlertDialogFooterProps, AlertDialogTitleProps, AlertDialogDescriptionProps, AlertDialogActionProps, AlertDialogCancelProps } from './components/alert-dialog'
export type { CollapsibleProps, CollapsibleTriggerProps, CollapsibleContentProps } from './components/collapsible'
export type { ContextMenuProps, ContextMenuTriggerProps, ContextMenuContentProps, ContextMenuItemProps, ContextMenuSeparatorProps, ContextMenuLabelProps, ContextMenuGroupProps } from './components/context-menu'
export type { HoverCardProps, HoverCardTriggerProps, HoverCardContentProps } from './components/hover-card'
export type { ComboboxProps, ComboboxOption } from './components/combobox'
export type { PaginationProps, PaginationItemProps } from './components/pagination'
export type { RadioGroupProps, RadioGroupItemProps } from './components/radio-group'
export type { SheetProps, SheetTriggerProps, SheetContentProps, SheetHeaderProps, SheetFooterProps, SheetTitleProps, SheetDescriptionProps } from './components/sheet'
export type { ScrollAreaProps, ScrollBarProps } from './components/scroll-area'
export type { NavigationMenuProps, NavigationMenuListProps, NavigationMenuItemProps, NavigationMenuTriggerProps, NavigationMenuContentProps, NavigationMenuLinkProps } from './components/navigation-menu'
export type { MenubarProps, MenubarMenuProps, MenubarTriggerProps, MenubarContentProps, MenubarItemProps, MenubarSeparatorProps, MenubarLabelProps, MenubarGroupProps } from './components/menubar'
export type { CommandProps, CommandInputProps, CommandListProps, CommandEmptyProps, CommandGroupProps, CommandItemProps, CommandSeparatorProps } from './components/command'
export type { CarouselProps, CarouselContentProps, CarouselItemProps, CarouselPreviousProps, CarouselNextProps, CarouselIndicatorProps } from './components/carousel'
export type { InputOTPProps, InputOTPGroupProps, InputOTPSlotProps } from './components/input-otp'
export type { ResizableProps, ResizableHandleProps, ResizablePanelProps } from './components/resizable'
export type { DatePickerProps, DatePickerInputProps, DatePickerContentProps, DatePickerCalendarProps } from './components/date-picker'
export type { AspectRatioProps } from './components/aspect-ratio'
export type { DrawerProps, DrawerTriggerProps, DrawerContentProps, DrawerHeaderProps, DrawerFooterProps, DrawerTitleProps, DrawerDescriptionProps } from './components/drawer'
export type { TypographyProps, TypographyH1Props, TypographyH2Props, TypographyH3Props, TypographyH4Props, TypographyH5Props, TypographyH6Props, TypographyPProps, TypographyBlockquoteProps, TypographyCodeProps, TypographyLeadProps, TypographyLargeProps, TypographySmallProps, TypographyMutedProps } from './components/typography'
export type { DataTableProps, DataTableColumn, DataTableHeaderProps, DataTableRowProps, DataTablePaginationProps } from './components/data-table'
export type { ChartProps, ChartData, BarChartProps, LineChartProps, PieChartProps } from './components/chart'
export type { SonnerProps, ToastProps as SonnerToastProps } from './components/sonner'
export type { FormProps, FormFieldProps, FormItemProps, FormLabelProps, FormControlProps, FormDescriptionProps, FormMessageProps } from './components/react-hook-form'
export type { ColorScheme } from './lib/colors'
